apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 600-k8s-forwarder-pve-xeno-tuana9a-com
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    repoURL: https://github.com/tuana9a/platform.git
    path: 600-k8s-forwarder-manifests/k8s-web-forwarder
    targetRevision: rock-n-roll
    helm:
      releaseName: pve-xeno-tuana9a-com 
      valueFiles:
        - values/pve-xeno-tuana9a-com.yaml
  destination:
    namespace: k8s-forwarder
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
