- name: Ensure folder .aws exists
  become: true
  ansible.builtin.file:
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0700"
    path: "/home/{{ ansible_user }}/.aws/"
    state: directory

- name: Copy aws credentials file
  copy:
    src: "{{ HOST_NAME }}/aws/credentials"
    dest: "/home/{{ ansible_user }}/.aws/credentials"
    force: true
