- name: Ensure .ssh dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "700"
    state: directory

- name: Copy script "ensure_authorized_keys.sh"
  become: true
  ansible.builtin.template:
    mode: "700"
    owner: "{{ ansible_user }}"
    src: "ensure_authorized_keys.sh"
    dest: "/usr/local/bin/ensure_authorized_keys.sh"
    force: true

- name: Sync authorized_keys cronjob
  loop: "{{ authorized_keys_items }}"
  ansible.builtin.cron:
    name: "authorized_keys:{{ item.name }}"
    minute: "*/5" # Every 5 minutes
    job: '/usr/local/bin/ensure_authorized_keys.sh "{{ item.url }}" >> /tmp/cronjob-authorized-keys.log 2>&1'
    state: "{{ item.state | default('present') }}"
