- name: Create a cronjob
  loop: "{{ cronjob_items }}"
  ansible.builtin.cron:
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    name: "{{ item.name }}"
    job: "{{ item.cmd }}"
    state: "{{ item.state | default('present') }}"
