- name: Copy script to remote
  become: true
  ansible.builtin.template:
    src: backup-nfs.sh
    dest: /usr/local/bin/backup-nfs.sh
    mode: "0700"
    owner: "{{ ansible_user }}"

- name: Create a cronjob for that
  loop: "{{ backup_nfs_items }}"
  ansible.builtin.cron:
    name: "backup-nfs.sh:{{ item.name }}"
    minute: "0"
    hour: "17"
    # quote item.path to support glob like /exports/nfs-client/coder-*
    job: "/usr/local/bin/backup-nfs.sh \"{{ item.path }}\" {{ item.name }} >> /tmp/backup-nfs-{{ item.name }}.log 2>&1"
    state: "{{ item.state | default('present') }}"
