- name: Install glab
  ansible.builtin.shell: |
    cd /tmp
    wget https://gitlab.com/gitlab-org/cli/-/releases/v1.39.0/downloads/glab_1.39.0_Linux_x86_64.tar.gz -O glab.tar.gz
    tar xzf glab.tar.gz
    sudo install -o root -g root -m 0755 bin/glab /usr/local/bin/glab
