- name: Install go
  become: true
  ansible.builtin.shell: |
    cd /tmp/
    wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
