- name: Ensure folder .aws exists
  become: true
  ansible.builtin.file:
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0700"
    path: "/home/{{ ansible_user }}/.aws/"
    state: directory

- name: Delete aws credentials file
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.aws/credentials"
    state: absent
