persistence:
  enabled: true
  storageClass: nfs-vdb
controller:
  ingress:
    enabled: true
    hostName: jenkins.tuana9a.com
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: "jenkins.tuana9a.com"
      external-dns.alpha.kubernetes.io/target: "103.232.121.190"
    hosts:
      - host: jenkins.tuana9a.com
    tls:
      - secretName: jenkins-tuana9a-com-tls
        hosts:
          - jenkins.tuana9a.com
