persistence:
  enabled: true
  storageClass: nfs-vdb
controller:
  additionalPlugins: []
  installPlugins: []
  image:
    repository: tuana9a/jenkins
    tag: git-eff2944e151836fad4a2869a0fe4617d702bb1cf
  ingress:
    enabled: true
    hostName: jenkins.tuana9a.com
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # external-dns.alpha.kubernetes.io/hostname: "jenkins.tuana9a.com"
      # external-dns.alpha.kubernetes.io/target: "xenomorph.tuana9a.com"
    hosts:
      - host: jenkins.tuana9a.com
    tls:
      - secretName: jenkins-tuana9a-com-tls
        hosts:
          - jenkins.tuana9a.com
  JCasC:
    authorizationStrategy: "" # disable here we already have it configured in 093-jenkins-JCasC
    securityRealm: "" # disable here we already have it configured in 093-jenkins-JCasC
  additionalExistingSecrets:
    - name: google-login
      keyName: client-secret
