apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: 502-coder-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  502-coder-jobs.yaml: |
    jobs:
      - script: |
          pipelineJob('502-coder-postgres-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/502-coder-postgres-backup.Jenkinsfile")
              }
            }
          }
