apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: jenkins
  name: 511-dkhptd-mongo-backup-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: SecretStore
  target:
    name: 511-dkhptd-mongo-backup-env
  dataFrom:
    - extract:
        key: dkhptd/mongo-backup/env
