apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: 511-dkhptd-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  511-dkhptd-jobs.yaml: |
    jobs:
      - script: |
          pipelineJob('511-dkhptd-dkhptd-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/511-dkhptd-mongo-backup.Jenkinsfile")
              }
            }
          }
