apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: all-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  all.yaml: |
    jobs:
      - script: |
          pipelineJob('vault-unseal') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-unseal.Jenkinsfile")
              }
            }
          }
          pipelineJob('vault-secret-store-token-renew') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-secret-store-token-renew.Jenkinsfile")
              }
            }
          }
          pipelineJob('vault-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 * * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-backup.Jenkinsfile")
              }
            }
          }
