apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: all-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  all.yaml: |
    jobs:
      - script: |
          pipelineJob('k8s-control-plane-etcd-defrag') {
            properties {
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/k8s-control-plane-etcd-defrag.Jenkinsfile")
              }
            }
          }
          pipelineJob('k8s-control-plane-backup-kubernetes') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/k8s-control-plane-backup-kubernetes.Jenkinsfile")
              }
            }
          }
          pipelineJob('511-dkhptd-mongo-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/511-dkhptd-mongo-backup.Jenkinsfile")
              }
            }
          }
          pipelineJob('502-coder-postgres-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/502-coder-postgres-backup.Jenkinsfile")
              }
            }
          }
          pipelineJob('vault-unseal') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-unseal.Jenkinsfile")
              }
            }
          }
          pipelineJob('vault-secret-store-token-renew') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-secret-store-token-renew.Jenkinsfile")
              }
            }
          }
          pipelineJob('vault-backup') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 * * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/vault-backup.Jenkinsfile")
              }
            }
          }
          multibranchPipelineJob('095-github-runners-terraform-plan-apply') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('1754893933') // date +%s
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/095-github-runners-terraform-plan-apply.Jenkinsfile')
              }
            }
            orphanedItemStrategy {
              discardOldItems {
                numToKeep(14)
              }
            }
            triggers {
              cron('* * * * *')
            }
          }
