apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: quality-of-life-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  timestamper.yaml: |
    unclassified:
      timestamper:
        allPipelines: true
  appearance.yaml: |
    appearance:
      themeManager:
        disableUserThemes: true
        theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
