apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing # this namespace is hardcoded afaik
spec:
  version: "1.14.2"
  workloads:
    - name: eventing-controller
      resources:
        - container: eventing-controller
          requests:
            cpu: 10m
            memory: 75M
          limits:
            cpu: 100m
            memory: 150M
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 50m
            memory: 125M
          limits:
            cpu: 100m
            memory: 200M
    - name: kafka-controller
      resources:
        - container: controller
          requests:
            cpu: 10m
            memory: 75M
          limits:
            cpu: 100m
            memory: 150M
    - name: mt-broker-controller
      resources:
        - container: mt-broker-controller
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M
    - name: mt-broker-filter
      resources:
        - container: filter
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M
    - name: mt-broker-ingress
      resources:
        - container: ingress
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M
