- hosts: zephyrus
  tasks:
    - import_tasks: ./tasks/cronjob_authorized_keys.yml
    - import_tasks: ./tasks/set_timezone.yml
    - import_tasks: ./tasks/install_tmux.yml
    - import_tasks: ./tasks/set_hostname.yml
    - import_tasks: ./tasks/cronjob_update_cloudflare_dns.yml
    - import_tasks: ./tasks/install_docker.yml
    - import_tasks: ./tasks/install_awscli.yml
    - import_tasks: ./tasks/install_wireguard.yml
    - import_tasks: ./tasks/wireguard_client.yml
    - import_tasks: ./tasks/remove_aws_credentials.yml
    - import_tasks: ./tasks/install_node_exporter.yml
    - import_tasks: ./tasks/rsync.yml
    - import_tasks: ./tasks/install_nginx.yml
    - import_tasks: ./tasks/install_nginx_exporter.yml
    - import_tasks: ./tasks/cronjob_backup_nginx.yml
    - import_tasks: ./tasks/disable_nginx_site_default.yml
