- hosts: xenomorph
  tasks:
    # - name: Delete old location kubeconfig
    #   become: true
    #   file:
    #     path: "/opt/kubeconfig"
    #     state: absent

    - name: Delete old current state load balancer ip
      file:
        path: /tmp/current-ingress-nginx-load-balancer-ip.txt
        state: absent

    # - name: Ensure kubeconfig directory
    #   ansible.builtin.file:
    #     path: "{{ lookup('env','HOME') }}/.kube"
    #     state: directory
    #     mode: "0700"

    - name: Delete old kubeconfig
      become: true
      file:
        path: "/opt/kubeconfig"
        state: absent

    - name: Copy script
      become: true
      ansible.builtin.template:
        src: update-ingress-nginx-load-balancer-ip.sh
        dest: /usr/local/bin/update-ingress-nginx-load-balancer-ip.sh
        mode: "0700"
        owner: "{{ ansible_user }}"

    - name: Disable cronjob
      ansible.builtin.cron:
        name: "update-ingress-nginx-load-balancer-ip.sh"
        minute: "*/1"
        job: "/usr/local/bin/update-ingress-nginx-load-balancer-ip.sh >> /tmp/update-ingress-nginx-load-balancer-ip.log 2>&1"
        disabled: true

    - name: Delete log
      file:
        path: /tmp/update-ingress-nginx-load-balancer-ip.log
        state: absent

    - name: Delete old overwrite flag
      copy:
        file: /tmp/overwrite-flag
        state: absent
