- hosts: k8s_first_control_plane
  tasks:
    - import_tasks: ./tasks/kubeadm_create_join_command.yml
    - name: set join command
      set_fact:
        join_command: "{{ create_join_command_output.stdout | trim }}"

- hosts: k8s_cluster
  tasks:
    - name: Copy facts
      set_fact:
        join_command: "{{ hostvars[groups['k8s_first_control_plane'][0]].join_command }}"
    - import_tasks: ./tasks/kubeadm_join.yml
      when: not kube_joined
