- hosts: xenomorph
  tasks:
    # - name: Delete old location kubeconfig
    #   become: true
    #   file:
    #     path: "/opt/kubeconfig"
    #     state: absent

    - name: Delete old current state load balancer ip
      file:
        path: /tmp/current-ingress-nginx-load-balancer-ip.txt
        state: absent

    # - name: Ensure kubeconfig directory
    #   ansible.builtin.file:
    #     path: "{{ lookup('env','HOME') }}/.kube"
    #     state: directory
    #     mode: "0700"

    - name: Copy kubeconfig to remote
      become: true
      copy:
        src: xenomorph/kubeconfig
        dest: "/opt/kubeconfig"
        mode: "0600"

    - name: Copy script to remote
      become: true
      ansible.builtin.template:
        src: update-ingress-nginx-load-balancer-ip.sh
        dest: /usr/local/bin/update-ingress-nginx-load-balancer-ip.sh
        mode: "0700"
        owner: "{{ ansible_user }}"
      vars:
        namespace: ingress-nginx

    - name: Create a cronjob for that
      ansible.builtin.cron:
        name: "update-ingress-nginx-load-balancer-ip.sh"
        minute: "*/1"
        job: "/usr/local/bin/update-ingress-nginx-load-balancer-ip.sh >> /tmp/update-ingress-nginx-load-balancer-ip.log 2>&1"

    - name: Clear current log
      copy:
        content: ""
        dest: /tmp/update-ingress-nginx-load-balancer-ip.log

    - name: Set overwrite flag
      copy:
        content: "1"
        dest: /tmp/overwrite-flag
