- hosts: xenomorph
  tasks:
    - name: Delete old current state load balancer ip
      ansible.builtin.file:
        path: /tmp/current-ingress-nginx-load-balancer-ip.txt
        state: absent

    - name: Delete update-ingress-nginx-load-balancer-ip.sh
      ansible.builtin.file:
        path: /usr/local/bin/update-ingress-nginx-load-balancer-ip.sh
        state: absent

    - name: Remove cronjob
      ansible.builtin.cron:
        name: "update-ingress-nginx-load-balancer-ip.sh"
        minute: "*/1"
        job: "/usr/local/bin/update-ingress-nginx-load-balancer-ip.sh >> /tmp/update-ingress-nginx-load-balancer-ip.log 2>&1"
        state: absent

    - name: Delete log
      ansible.builtin.file:
        path: /tmp/update-ingress-nginx-load-balancer-ip.log
        state: absent

    - name: Delete old overwrite flag
      ansible.builtin.file:
        path: /tmp/overwrite-flag
        state: absent

    - name: Delete old location kubeconfig
      ansible.builtin.file:
        path: "/opt/kubeconfig"
        state: absent

    - name: Delete .kube directory
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: absent
