- hosts: k8s_control_plane
  tasks:
    - import_tasks: ./tasks/install_unzip.yml # required for install awscli
    - import_tasks: ./tasks/install_awscli.yml
    # etcd is already installed
    # - import_tasks: ./tasks/install_etcd.yml
