persistence:
  enabled: true
  storageClassName: longhorn
  size: 2Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: loki
        type: loki
        url: http://loki-gateway.loki-system.svc.cluster.local
        # server returned HTTP status 401 Unauthorized (401): no org id
        # https://github.com/grafana/loki/issues/7081
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "1"
      - name: k8s-node-exporter
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
