global:
  enabled: true
server:
  standalone:
    enabled: false
  ha:
    enabled: true
    raft:
      enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: nfs-vdb
  affinity: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: "vault.tuana9a.com"
      external-dns.alpha.kubernetes.io/target: "parkingx.tuana9a.com"
    hosts:
      - host: vault.tuana9a.com
    tls:
      - secretName: vault-tuana9a-com-tls
        hosts:
          - vault.tuana9a.com
