nfs:
  server: "192.168.56.7"
  path: /exports/vdb/
replicaCount: "3"
storageClass:
  create: "true"
  defaultClass: "false"
  name: nfs-vdb
  allowVolumeExpansion: "true"
  reclaimPolicy: Delete
  archiveOnDelete: "true"
  volumeBindingMode: Immediate
