- name: Remove old backup script
  become: true
  ansible.builtin.file:
    state: absent
    path: /opt/backup-haproxy.sh

- name: Copy script to remote
  become: true
  ansible.builtin.template:
    src: backup-haproxy.sh
    dest: /usr/local/bin/backup-haproxy.sh
    mode: "0755"
    owner: "{{ ansible_user }}"

- name: Create a cronjob for that
  ansible.builtin.cron:
    name: "backup-haproxy.sh"
    minute: "0" # TODO: config
    hour: "0"   # TODO: config
    job: "/usr/local/bin/backup-haproxy.sh > /tmp/backup-haproxy.log 2>&1"
