HOST_NAME: db
parted:
  dev_path: /dev/vdb
  mount_path: /data/
openvpn_client_items:
  - file: db/db-zephyrus.ovpn
    name: db-zephyrus
update_dns_items:
  - record_name: db.z.tuana9a.com
    extract_ip: $(/usr/sbin/ip addr show tun0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
rsync_items:
  - src: db/mongodb/
    dest: /opt/mongodb/
  - src: db/postgres/
    dest: /opt/postgres/
  - src: db/rabbitmq/
    dest: /opt/rabbitmq/
