- name: Remove old backup setup
  become: true
  ansible.builtin.file:
    state: absent
    path: /opt/backup-nginx.sh

- name: Disable old cronjob
  ansible.builtin.cron:
    name: "backup-nginx.sh"
    minute: "0"
    hour: "0"
    job: "/opt/backup-nginx.sh > /tmp/backup-nginx.log 2>&1"
    state: absent

- name: Copy script to remote
  become: true
  ansible.builtin.template:
    src: backup-nginx.v2.sh
    dest: /usr/local/bin/backup-nginx.v2.sh
    mode: "0700"
    owner: "{{ ansible_user }}"

- name: Create a cronjob for that
  ansible.builtin.cron:
    name: "backup-nginx.v2.sh"
    minute: "0"
    hour: "0"
    job: "/usr/local/bin/backup-nginx.v2.sh > /tmp/backup-nginx.v2.log 2>&1"
