- name: docker-compose down
  become: true
  loop: "{{ compose_items }}"
  shell:
    cmd: "/usr/local/bin/docker-compose down -v"
    chdir: "{{ item.dir }}"

- name: docker-compose up
  become: true
  loop: "{{ compose_items }}"
  shell:
    cmd: "/usr/local/bin/docker-compose up -d"
    chdir: "{{ item.dir }}"
