- name: Install zsh package
  become: true
  apt:
    name:
      - zsh
    state: present

- name: Ensure zsh is the default shell
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: "/usr/bin/zsh"
