- name: Stop and disable service
  become: true
  ansible.builtin.service:
    name: port-forward-ingress
    state: stopped
    enabled: false

- name: Remove script
  become: true
  file:
    path: /usr/local/bin/port-forward-ingress-nginx.sh
    state: absent

- name: Remove systemd service file
  become: true
  file:
    path: /etc/systemd/system/port-forward-ingress.service
    state: absent

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes
