- name: rsync conf.d dir to remote
  become: true
  when: nginx.conf_d is defined
  ansible.posix.synchronize:
    src: "{{ nginx.conf_d }}"
    recursive: true
    delete: true
    dest: /etc/nginx/conf.d/
    rsync_opts:
      - "--exclude=*.j2"

- name: rsync stream.conf.d dir to remote
  become: true
  when: nginx.stream_conf_d is defined
  ansible.posix.synchronize:
    src: "{{ nginx.stream_conf_d }}"
    recursive: true
    delete: true
    dest: /etc/nginx/stream.conf.d/
    rsync_opts:
      - "--exclude=*.j2"

- name: Reload nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
