- name: Upload .conf file
  loop: "{{ wireguard_client_items }}"
  become: true
  copy:
    src: "{{ item.file }}"
    dest: "/etc/wireguard/{{ item.name }}.conf"
    mode: "0644"

- name: Setup wireguard service
  loop: "{{ wireguard_client_items }}"
  become: true
  service:
    name: "wg-quick@{{ item.name }}"
    state: "{{ item.state | default('restarted') }}"
    enabled: "{{ item.enabled | default('true') }}"
