apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-login
spec:
  type: kv-v1
  mount: kv
  path: grafana/admin-login
  destination:
    name: admin-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default
