apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-prometheus
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true
