config:
  clients:
    - url: http://loki-gateway.loki-system.svc.cluster.local/loki/api/v1/push
      # server returned HTTP status 401 Unauthorized (401): no org id
      # https://github.com/grafana/loki/issues/7081
      tenant_id: 1
