kind: Service
apiVersion: v1
metadata:
  name: forward-kourier
  namespace: t9stbot
spec:
  type: ExternalName
  externalName: kourier-internal.knative-serving.svc.cluster.local
  ports:
    - port: 80
