# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    container_name: postgres-16
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    shm_size: 128mb
    network_mode: host
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data/postgres/data/:/var/lib/postgresql/data/
