apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-restore
  namespace: dkhptd
spec:
  template:
    spec:
      initContainers:
        - name: download
          image: amazon/aws-cli:latest
          command:
            - "sh"
            - "-c"
            - |
              OBJECT_KEY=dkhptd/mongo-dump-2024.12.01.07.tar.gz
              aws s3api --endpoint-url ${S3_ENDPOINT} get-object --bucket ${BUCKET_NAME} --key $OBJECT_KEY /data/dump.tar.gz
              echo =====
              ls -la /data/
          envFrom:
            - secretRef:
                name: dkhptd-mongo-backup-env
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: unzip
          image: busybox:latest
          command:
            - "sh"
            - "-c"
            - |
              cd /data
              echo =====
              tar -xzvf dump.tar.gz dump
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: restore
          image: mongo:4.4
          command:
            - "sh"
            - "-c"
            - |
              echo =====
              mongorestore $MONGO_CONNECTION_STRING /data/dump
          envFrom:
            - secretRef:
                name: dkhptd-mongo-backup-env
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: done
          image: busybox:latest
          command: ["sh", "-c", "echo done"]
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
