apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-migrate
  namespace: dkhptd
spec:
  template:
    spec:
      initContainers:
        - name: dump
          image: mongo:4.4
          command:
            - "sh"
            - "-c"
            - |
              mongodump $MONGO_CONNECTION_STRING --out=/data/dump
              echo ========================
              ls -l /data/dump
          envFrom:
            - secretRef:
                name: dkhptd-mongo-migrate-env
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: restore
          image: mongo:4.4
          command:
            - "sh"
            - "-c"
            - |
              mongorestore $MONGO_CONNECTION_STRING_NEW /data/dump
          envFrom:
            - secretRef:
                name: dkhptd-mongo-migrate-env
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: done
          image: busybox:latest
          command: ["sh", "-c", "echo done"]
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
