apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 120-k8s-namespaces
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 120-k8s-namespaces
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
