# destroying helm cert-manager will not destroy crds luckily because of this anotation
# "helm.sh/resource-policy": keep
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator-k8s-cobi-tuana9a
  namespace: argocd
spec:
  project: default
  sources:
    - chart: vault-secrets-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: "0.9.0"
      helm:
        releaseName: vault-secrets-operator
        valueFiles:
          - $values/195-vault-secrets-operator-k8s-cobi-tuana9a/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
