apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 195-vault-manifests-k8s-cobi-tuana9a
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 195-vault-manifests-k8s-cobi-tuana9a
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
