apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 300-grafana
  namespace: argocd
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.6.4
      helm:
        releaseName: grafana
        valueFiles:
          - $values/300-grafana/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
