apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 300-promtail
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  sources:
    - chart: promtail
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.16.6
      helm:
        releaseName: promtail
        valueFiles:
          - $values/300-promtail/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: promtail
  syncPolicy:
    automated:
      # prune: false
      selfHeal: true
