apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 300-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.20.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/300-prometheus/values.yaml
          - $values/300-prometheus/alert-values.yaml
          - $values/300-prometheus/alert-msg-template-values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  # NOTE: wait https://github.com/prometheus/alertmanager/pull/3728 to be released
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
