apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 300-grafana-manifests
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 300-grafana-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
