controller:
  service:
    type: "LoadBalancer"
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ingress-nginx.svc.k8s-internal.tuana9a.com
  autoscaling:
    enabled: true
  resources:
    limits:
      cpu: 150m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 200Mi
