controller:
  service:
    type: "LoadBalancer"
    nodePorts:
      http: 30080
      https: 30443
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: ingress-nginx.svc.k8s-internal.tuana9a.com
  autoscaling:
    enabled: true
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 250Mi
