---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dkhptd-scheduler
  namespace: dkhptd
spec:
  type: kv-v1
  mount: kv
  path: dkhptd/scheduler/env
  destination:
    name: dkhptd-scheduler
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault/secrets-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkhptd-scheduler
  namespace: dkhptd
data:
  HELLO: WORLD # dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkhptd-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkhptd-scheduler
  template:
    metadata:
      labels:
        app: dkhptd-scheduler
    spec:
      containers:
        - name: dkhptd-scheduler
          image: tuana9a/dkhptd-scheduler:2024.08.16.055606
          envFrom:
            - configMapRef:
                name: dkhptd-scheduler
            - secretRef:
                name: dkhptd-scheduler
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
