apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dkhptd-mongo-backup-env
  namespace: dkhptd
spec:
  type: kv-v1
  mount: kv
  path: dkhptd/mongo-backup/env
  destination:
    name: dkhptd-mongo-backup-env
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default
