# kourier service is living on namespace: knative-serving so need a forwarder in each namespace that use knative
---
kind: Service
apiVersion: v1
metadata:
  name: forward-kourier
  namespace: default
spec:
  type: ExternalName
  externalName: kourier-internal.knative-serving.svc.cluster.local
  ports:
    - port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: forward-kourier
  namespace: t9stbot
spec:
  type: ExternalName
  externalName: kourier-internal.knative-serving.svc.cluster.local
  ports:
    - port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: forward-kourier
  namespace: dkhptd
spec:
  type: ExternalName
  externalName: kourier-internal.knative-serving.svc.cluster.local
  ports:
    - port: 80
