apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
# https://knative.dev/docs/install/operator/knative-with-operators/#create-the-knative-serving-custom-resource
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving # this namespace is hardcoded afaik
spec:
  version: "1.14.1"
  ingress:
    istio:
      enabled: false
    kourier:
      enabled: true
  config:
    network:
      # limited support ingress-class https://github.com/knative/serving/issues/10417
      ingress-class: "kourier.ingress.networking.knative.dev"
    domain:
      "kn.tuana9a.com": ""
  workloads:
    - name: controller
      resources:
        - container: controller
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 20m
            memory: 100Mi
    - name: webhook
      resources:
        - container: webhook
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 20m
            memory: 50Mi
    - name: activator
      resources:
        - container: activator
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 20m
            memory: 50Mi
    - name: autoscaler
      resources:
        - container: autoscaler
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 20m
            memory: 50Mi
    - name: autoscaler-hpa
      resources:
        - container: autoscaler-hpa
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 20m
            memory: 50Mi
