apiVersion: batch/v1
kind: Job
metadata:
  name: coder-postgres-migrate
  namespace: coder
spec:
  template:
    spec:
      initContainers:
        - name: dump
          image: postgres:16
          command:
            - "sh"
            - "-c"
            - |
              export PGPASSWORD=$PG_PASS
              echo ========================
              pg_dump -h $PG_HOST -p ${PG_PORT:-5432} -U $PG_USER -d $PG_DATABASE > /data/dump.sql
              echo ========================
              head /data/dump.sql
              echo ========================
          envFrom:
            - secretRef:
                name: coder-postgres-migrate-env
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: restore
          image: postgres:16
          command:
            - "sh"
            - "-c"
            - |
              export PGPASSWORD=$PG_PASS_NEW
              echo ========================
              psql -h $PG_HOST_NEW -p ${PG_PORT:-5432} -U $PG_USER_NEW -d $PG_DATABASE -f /data/dump.sql
          envFrom:
            - secretRef:
                name: coder-postgres-migrate-env
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: done
          image: busybox:latest
          command: ["sh", "-c", "echo done"]
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
