apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-control-plane-jobs-jcasc
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  k8s-control-plane-jobs.yaml: |
    jobs:
      - script: |
          pipelineJob('k8s-control-plane-etcd-defrag') {
            properties {
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/k8s-control-plane-etcd-defrag.Jenkinsfile")
              }
            }
          }
      - script: |
          pipelineJob('k8s-control-plane-backup-kubernetes') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('rock-n-roll')
                  }
                }
                scriptPath(".jenkins/k8s-control-plane-backup-kubernetes.Jenkinsfile")
              }
            }
          }
