apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hcr
  namespace: dkhptd
spec:
  template:
    spec:
      containers:
        - image: tuana9a/hcr
          imagePullPolicy: Always
          env:
            - name: DEVICE
              value: "cpu"
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
