---
- name: Setup mongo backup
  hosts: mongo_backup
  vars:
    MONGODB_TOOLS_VERSION: "100.5.0"
    MONGODB_TOOLS_URL: "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-{{ MONGODB_TOOLS_VERSION }}.tgz"
  tasks:
    - name: Create temp directory
      ansible.builtin.file:
        path: "/tmp/mongodb-tools"
        state: directory

    - name: Download MongoDB Tools
      ansible.builtin.get_url:
        url: "{{ MONGODB_TOOLS_URL }}"
        dest: "/tmp/mongodb-tools.tar.gz"

    - name: Extract MongoDB Tools
      ansible.builtin.unarchive:
        src: /tmp/mongodb-tools.tar.gz
        dest: /tmp
        remote_src: true

    - name: Copy MongoDB Tools to /usr/local/bin/
      become: true
      ansible.builtin.copy:
        src: /tmp/mongodb-database-tools-ubuntu2004-x86_64-{{ MONGODB_TOOLS_VERSION }}/bin/
        dest: /usr/local/bin/
        remote_src: yes
      with_fileglob: "*"

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "/tmp/mongodb-database-tools-ubuntu2004-x86_64-{{ MONGODB_TOOLS_VERSION }}"
        state: absent

    - name: Clean up downloaded tarball
      ansible.builtin.file:
        path: "/tmp/mongodb-tools.tar.gz"
        state: absent

    - name: Copy script to remote
      become: true
      ansible.builtin.template:
        src: backup-mongo.sh
        dest: /opt/backup-mongo.sh
        mode: "0755"

    - name: Create a cronjob for that
      ansible.builtin.cron:
        name: "backup-mongo.sh"
        minute: "0"
        hour: "0"
        job: "/opt/backup-mongo.sh > /tmp/backup-mongo.log 2>&1"
