---
- name: Setup nginx
  hosts: nginx
  tasks:
    - name: Default copy nginx.conf
      when: nginx_conf_file is not defined
      set_fact:
        nginx_conf_file: nginx.conf

    - name: Copy nginx.conf
      become: true
      ansible.builtin.copy:
        src: "{{ nginx_conf_file }}"
        dest: /etc/nginx/nginx.conf

    - name: Prepare stream.conf.d
      become: true
      ansible.builtin.file:
        path: /etc/nginx/stream.conf.d
        owner: root
        group: root
        mode: "755"
        state: directory

    # - name: Copy config to remote
    #   become: true
    #   ansible.builtin.copy:
    #     src: "{{ item }}"
    #     dest: "/etc/nginx/conf.d/{{ item | basename }}"
    #   with_fileglob:
    #     - "{{ conf_d }}/*"

    - name: Default empty conf.d folder
      when: conf_d is not defined
      set_fact:
        conf_d: empty/

    - name: rsync conf.d dir to remote
      become: true
      ansible.posix.synchronize:
        src: "{{ conf_d }}"
        recursive: true
        delete: true
        dest: /etc/nginx/conf.d/

    - name: Default empty stream.conf.d folder
      when: stream_conf_d is not defined
      set_fact:
        stream_conf_d: empty/

    - name: rsync stream.conf.d dir to remote
      become: true
      ansible.posix.synchronize:
        src: "{{ stream_conf_d }}"
        recursive: true
        delete: true
        dest: /etc/nginx/stream.conf.d/

    - name: Reload nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded
