- hosts: tuana9a_dev
  tasks:
    - import_tasks: ./tasks/copy_id_rsa.yml
    - import_tasks: ./tasks/copy_aws_credentials.yml
    - import_tasks: ./tasks/copy_gitconfig.yml
    - name: copy .zshrc
      copy:
        src: tuana9a-dev/.zshrc
        dest: ~/.zshrc
