- hosts: wispswap_bot
  vars_files:
    - ./var_files/wispswap-bot.yml
    - ./var_files/tuana9a-device-authorized-keys.yml
  tasks:
    - import_tasks: ./tasks/cronjob_authorized_keys.yml
    - import_tasks: ./tasks/set_timezone.yml
    - import_tasks: ./tasks/set_hostname.yml
    - import_tasks: ./tasks/parted.yml
    - import_tasks: ./tasks/copy_id_rsa.yml
    - import_tasks: ./tasks/install_docker.yml
    - import_tasks: ./tasks/install_awscli.yml
    - import_tasks: ./tasks/install_node_exporter.yml
    - import_tasks: ./tasks/openvpn_client.yml
    - import_tasks: ./tasks/rsync.yml
    - import_tasks: ./tasks/install_nvm.yml
