HOST_NAME: orisis
rsync_items:
  - src: orisis/prometheus/
    dest: /opt/prometheus/
compose_items:
  - dir: /opt/prometheus/
update_dns_items:
  - record_name: o.o.tuana9a.com
    extract_ip: $(/sbin/ifconfig tun0 | grep 'inet ' | awk '{print $2}')
    state: absent
  - record_name: orisis.tuana9a.com
    extract_ip: $(/usr/bin/curl ifconfig.me)
    state: absent
  - record_name: ors.tuana9a.com
    extract_ip: $(/usr/bin/curl ifconfig.me)
    state: absent
