apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paste
  namespace: stuffs
spec:
  template:
    spec:
      containers:
        - image: tuana9a/paste-go:2.0.0-546fe292
          env:
            - name: BIND
              value: "0.0.0.0"
            - name: REDIS_URL
              value: "redis-0.redis:6379"
            - name: REDIS_PASS
              value: ""
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paste
  namespace: stuffs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: "paste.stuffs.kn.tuana9a.com"
    external-dns.alpha.kubernetes.io/target: "xenomorph.tuana9a.com"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paste.stuffs.kn.tuana9a.com
      secretName: paste-stuffs-kn-tuana9a-com-tls
  rules:
    - host: paste.stuffs.kn.tuana9a.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: forward-kourier
                port:
                  number: 80
