apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-v2-migration
  namespace: coder
spec:
  template:
    spec:
      initContainers:
        - name: postgres-dump
          image: postgres:16
          command:
            - "sh"
            - "-c"
            - |
              export PGPASSWORD=$PG_PASS
              echo ========================
              pg_dump -h $PG_HOST -p ${PG_PORT:-5432} -U $PG_USER -d $PG_DATABASE > /data/dump.sql
              echo ========================
              head /data/dump.sql
              echo ========================
          envFrom:
            - configMapRef:
                name: coder-postgres-v2-migration
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: postgres-restore
          image: postgres:16
          command:
            - "sh"
            - "-c"
            - |
              export PGPASSWORD=$PG_PASS_V2
              echo ========================
              psql -h $PG_HOST_V2 -p ${PG_PORT:-5432} -U $PG_USER_V2 -d $PG_DATABASE -f /data/dump.sql
          envFrom:
            - configMapRef:
                name: coder-postgres-v2-migration
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: postgres-v2-migration
          image: busybox:latest
          command: ["sh", "-c", "echo migration v2 complete"]

      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
