host: "trithuctre.com"
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/target: "xenomorph.tuana9a.com"
target:
  ip: 192.168.56.1
  port: 8080
