- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name:
      - ca-certificates
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Create keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    mode: "0755"
    state: directory

- name: Download and install Docker GPG key
  become: true
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Add read permission to /etc/apt/keyrings/docker.gpg
  become: true
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Get Ubuntu release version
  shell: lsb_release -cs
  register: ubuntu_version

- name: Get architecture
  shell: dpkg --print-architecture
  register: architecture

- name: Add Docker repository
  become: true
  shell: "echo deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable > /etc/apt/sources.list.d/docker.list"

- name: Install Docker engine
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Install docker-compose from official github repo
  become: true
  get_url:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"
