loki:
  commonConfig:
    replication_factor: 1 # Default is 3, required as SingleBinary
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    max_label_names_per_series: 20
    retention_period: 168h # 7 days

deploymentMode: SingleBinary
singleBinary:
  replicas: 1

# Cache config
resultsCache:
  allocatedMemory: 2000

chunksCache:
  allocatedMemory: 2000

# Enable minio for storage
minio:
  enabled: true
  persistence:
    storageClass: nfs-vdb
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
