alertmanager:
  image:
    repository: quay.io/prometheus/alertmanager
    pullPolicy: IfNotPresent
    tag: "v0.28.0" # fix https://github.com/prometheus/alertmanager/pull/3728
  persistence:
    storageClass: nfs-vdb
    size: 2Gi
  config:
    enabled: true
    route:
      receiver: "discord"
    receivers:
      - name: "discord"
        discord_configs:
          - webhook_url_file: /etc/discord_webhook_url.txt
  extraSecretMounts:
    - name: discord-webhook-url
      mountPath: /etc/discord_webhook_url.txt
      subPath: discord_webhook_url.txt
      secretName: alertmanager
      readOnly: true
