server:
  global:
    scrape_interval: 15s
  persistentVolume:
    storageClass: nfs-vdb
    size: 15Gi
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
