---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-postgres-v3-env
  namespace: coder
spec:
  type: kv-v1
  mount: kv
  path: coder/postgres/env
  destination:
    name: coder-postgres-v3-env
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault/secrets-operator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-v3
  namespace: coder
spec:
  replicas: 1
  serviceName: postgres-v3
  selector:
    matchLabels:
      app: postgres-v3
  template:
    metadata:
      labels:
        app: postgres-v3
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef:
                name: coder-postgres-v3-env
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 1000m
              memory: 1000M
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: nfs-vdb
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-v3
  namespace: coder
  labels:
    app: postgres-v3
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres-v3
