apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-postgres-env
  namespace: coder
spec:
  type: kv-v1
  mount: kv
  path: coder/postgres/env
  destination:
    name: coder-postgres-env
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default