apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: coder
spec:
  replicas: 1
  serviceName: internal
  selector:
    matchLabels:
      app: postgres
      internal: "1"
  template:
    metadata:
      labels:
        app: postgres
        internal: "1"
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef:
                name: coder-postgres-env
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 300M
            limits:
              cpu: 500m
              memory: 500M
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: nfs-vdb
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
