apiVersion: v1
kind: Pod
metadata:
  name: workdir-debug
  namespace: hcr
spec:
  volumes:
    - name: hcr-workdir
      persistentVolumeClaim:
        claimName: hcr-workdir
  containers:
    - image: alpine
      name: alpine
      workingDir: /workdir
      volumeMounts:
        - name: hcr-workdir
          mountPath: /workdir
      command: ["sleep", "1d"]
