---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t9stbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t9stbot
  template:
    metadata:
      labels:
        app: t9stbot
    spec:
      containers:
        - name: t9stbot
          image: tuana9a/t9stbot:master-0f4f059b
          envFrom:
            - configMapRef:
                name: t9stbot
            - secretRef:
                name: t9stbot
          command: ["node", "main-webhook.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: t9stbot
spec:
  selector:
    app: t9stbot
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
