---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d9stbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d9stbot
  template:
    metadata:
      labels:
        app: d9stbot
    spec:
      containers:
        - name: d9stbot
          image: tuana9a/d9stbot:git-0c2387f5
          envFrom:
            - configMapRef:
                name: d9stbot
            - secretRef:
                name: d9stbot
          command: ["node", "main.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: d9stbot
spec:
  selector:
    app: d9stbot
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
