apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      securityContext:
        # ubuntu runs as root by default, it is recommended or even mandatory in some environments (such as pod security admission "restricted") to run as a non-root user.
        runAsUser: 1000
    - name: set-params
      image: busybox
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: workdir
          mountPath: /data

    - name: dump
      image: postgres:16
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: workdir
          mountPath: /data
      envFrom:
        - secretRef:
            name: 502-coder-postgres-backup-env

    - name: zip
      image: busybox:latest
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: workdir
          mountPath: /data

    - name: upload
      image: amazon/aws-cli:2.18.0
      command:
        - sleep
      args:
        - infinity
      envFrom:
        - secretRef:
            name: 502-coder-postgres-backup-env
      volumeMounts:
        - name: workdir
          mountPath: /data

    - name: notify
      image: alpine/curl
      command:
        - sleep
      args:
        - infinity
      envFrom:
        - secretRef:
            name: 502-coder-postgres-backup-env
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumeMounts:
        - name: workdir
          mountPath: /data
  restartPolicy: Never
  volumes:
    - name: workdir
      emptyDir: {}
