apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - secretRef:
            name: 511-dkhptd-mongo-backup-env
      volumeMounts:
        - name: workdir
          mountPath: /data

    - name: mongo
      image: mongo:4.4
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: workdir
          mountPath: /data
      envFrom:
        - secretRef:
            name: 511-dkhptd-mongo-backup-env

    - name: awscli
      image: amazon/aws-cli:2.18.0
      command:
        - sleep
      args:
        - infinity
      envFrom:
        - secretRef:
            name: 511-dkhptd-mongo-backup-env
      volumeMounts:
        - name: workdir
          mountPath: /data

  restartPolicy: Never
  volumes:
    - name: workdir
      emptyDir: {}
