apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      securityContext:
        # ubuntu runs as root by default, it is recommended or even mandatory in some environments (such as pod security admission "restricted") to run as a non-root user.
        runAsUser: 1000
    - name: kp
      image: tuana9a/kp:dev-78b56d8
      command:
        - /bin/sh
      args:
        - -c
        - "sleep infinity"
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
    - name: ansible
      image: alpine/ansible:2.17.0
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
    - name: notify
      image: alpine/curl
      command:
        - sleep
      args:
        - infinity
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
  volumes:
    - name: secrets
      secret:
        secretName: backup-kubernetes
    - name: workdir
      emptyDir: {}
