apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
    - name: kp
      image: tuana9a/kp:dev-78b56d8
      command:
        - /bin/sh
      args:
        - -c
        - "sleep infinity"
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
  volumes:
    - name: secrets
      secret:
        secretName: backup-kubernetes
    - name: workdir
      emptyDir: {}
