apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
    - name: vault
      image: hashicorp/vault:1.17.2
      command: ["sleep", "infinity"]
      envFrom:
        - secretRef:
            name: vault-tuana9a-com-token
      volumeMounts:
        - name: workdir
          mountPath: "/workdir"
  volumes:
    - name: workdir
      emptyDir: {}
