# https://knative.dev/docs/install/operator/knative-with-operators/#create-the-knative-serving-custom-resource
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.14.1"
  config:
    network:
      ingress-class: "kong"
    domain:
      "kn.tuana9a.com": ""
  workloads:
    - name: controller
      resources:
        - container: controller
          resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
    - name: webhook
      resources:
        - container: webhook
          resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
    - name: activator
      resources:
        - container: activator
          resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
    - name: autoscaler
      resources:
        - container: autoscaler
          resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
    - name: autoscaler-hpa
      resources:
        - container: autoscaler-hpa
          resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
