apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.14.2"
  source:
    kafka:
      enabled: true
  workloads:
    - name: eventing-controller
      resources:
        - container: eventing-controller
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 50m
            memory: 100M
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 50m
            memory: 100M
    - name: kafka-controller
      resources:
        - container: controller
          requests:
            cpu: 10m
            memory: 50M
          limits:
            cpu: 50m
            memory: 100M
