version: "3"

services:
  hcr:
    image: tuana9a/hcr
    container_name: hcr
    env_file: .env
    restart: unless-stopped
    networks:
      net1:
        ipv4_address: 172.20.21.4

networks:
  net1:
    ipam:
      config:
        - subnet: 172.20.21.0/24
