ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: "grafana.tuana9a.com"
    external-dns.alpha.kubernetes.io/target: "parkingx.tuana9a.com"
  hosts:
    - "grafana.tuana9a.com"
  tls:
    - secretName: grafana-tuana9a-com-tls
      hosts:
        - "grafana.tuana9a.com"
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
grafana.ini:
  security:
    disable_brute_force_login_protection: "false"
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "admin-login"
  userKey: admin-user
  passwordKey: admin-password
