ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: "grafana.tuana9a.com"
    external-dns.alpha.kubernetes.io/target: "parkingx.tuana9a.com"
  hosts:
    - "grafana.tuana9a.com"
  tls:
    - secretName: grafana-tuana9a-com-tls
      hosts:
        - "grafana.tuana9a.com"
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource:
        - name: DS_PROMETHEUS
          value: prometheus
    Kubernetes_System_CoreDNS:
      gnetId: 15762
      revision: 19
      datasource:
        - name: DS_PROMETHEUS
          value: prometheus
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
grafana.ini:
  security:
    disable_brute_force_login_protection: "false"
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "admin-login"
  userKey: admin-user
  passwordKey: admin-password
