persistence:
  enabled: true
  storageClassName: nfs-vdb
  size: 2Gi
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: "grafana.tuana9a.com"
    external-dns.alpha.kubernetes.io/target: "zione.tuana9a.com"
  hosts:
    - "grafana.tuana9a.com"
  tls:
    - secretName: grafana-tuana9a-com-tls
      hosts:
        - "grafana.tuana9a.com"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true
      - name: loki
        type: loki
        url: http://loki-gateway.loki-system.svc.cluster.local
        # server returned HTTP status 401 Unauthorized (401): no org id
        # https://github.com/grafana/loki/issues/7081
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "1"
