apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-ingress-lb
  namespace: ingress-nginx
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-ingress-lb-binding
  namespace: ingress-nginx
subjects:
  - kind: User
    name: k8s-ingress-lb
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: k8s-ingress-lb
  apiGroup: rbac.authorization.k8s.io
