name: "dns terraform plan apply"

on:
  workflow_dispatch:
  push:
    paths:
      - "023-dns/**"
      - ".github/workflows/023-dns-terraform-plan-apply*"
    branches:
      - rock-n-roll

env:
  GCP_PROJECT_ID: tuana9a
  GCP_PROJECT_ID_NUM: 474326114337
  GCP_SERVICE_ACCOUNT: terraform-state-editor@tuana9a.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_POOL: github
  GCP_WORKLOAD_IDENTITY_POOL_PROVIDER: github-tuana9a
  WORKING_DIR: 023-dns/
  VAULT_TOKEN: "${{ secrets.DNS_UPDATER_VAULT_TOKEN }}"
  PLAN_ARTIFACT_NAME: ${{ github.run_id }}-${{ github.run_attempt }}-terraform-plan
jobs:
  plan:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_ID_NUM }}/locations/global/workloadIdentityPools/${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ env.GCP_WORKLOAD_IDENTITY_POOL_PROVIDER }}"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"
      - id: init
        name: init
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform init
      - id: plan
        name: plan
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform plan -out=tfplan.out
      - id: upload-plan
        name: upload-plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLAN_ARTIFACT_NAME }}
          path: "${{ env.WORKING_DIR }}/tfplan.out"
  apply:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    needs: [plan]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_ID_NUM }}/locations/global/workloadIdentityPools/${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ env.GCP_WORKLOAD_IDENTITY_POOL_PROVIDER }}"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"
      - id: init
        name: init
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform init
      - id: download-plan
        name: download-plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLAN_ARTIFACT_NAME }}
          path: "${{ env.WORKING_DIR }}"
      - id: apply
        name: apply
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform apply -auto-approve tfplan.out
      - id: set-status-ok
        name: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV
  notify:
    runs-on: ubuntu-latest
    needs: [plan, apply]
    if: ${{ always() }}
    steps:
      - id: notify
        name: notify
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name=$github_workflow
          MESSAGE="${status:-bad} $workflow_name $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
