name: check terraform key

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-terraform-key:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - id: check-terraform-key
        run: |
          ./scripts/check-terraform-key.sh

      - name: Notify
        if: ${{ always() }}
        run: |
          MESSAGE="${{ github.workflow }} $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
