name: "check terraform key"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-terraform-key:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - id: check-terraform-key
        run: ./scripts/check-terraform-key.sh
      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV
