name: "docker build push openssh"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Base image tag from original alpine image"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tuana9a
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set BUILD_TAG
        working-directory: "docker/openssh"
        run: |
          BUILD_TAG=${{ inputs.tag }}
          echo "BUILD_TAG=${BUILD_TAG}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/openssh
          file: docker/openssh/Dockerfile
          build-args: "BUILD_TAG=${{ env.BUILD_TAG }}"
          push: true
          tags: tuana9a/openssh:${{ env.BUILD_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV

      - name: Notify
        if: ${{ always() }}
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name=$github_workflow
          MESSAGE="${status:-bad} $workflow_name $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
