name: "docker build push coder"

on:
  workflow_dispatch:
    inputs:
      filepath:
        type: string
        description: which filepath will be image tag

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tuana9a
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/coder
          file: docker/coder/${{ github.event.inputs.filepath }}.Dockerfile
          push: true
          tags: tuana9a/coder:${{ github.event.inputs.filepath }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV

      - name: Notify
        if: ${{ always() }}
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name=$github_workflow
          build_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          MESSAGE="${status:-bad} $workflow_name \`tuana9a/coder:${{ github.event.inputs.filepath }}\` $build_url"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
