name: "docker build push coder minimal"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docker/coder/minimal.Dockerfile"
      - ".github/workflows/docker-build-push-coder-minimal*"
  push:
    branches:
      - main
    paths:
      - "docker/coder/minimal.Dockerfile"
      - ".github/workflows/docker-build-push-coder-minimal*"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tuana9a
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/coder
          file: docker/coder/minimal.Dockerfile
          push: true
          tags: tuana9a/coder:minimal
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV

      - name: Notify
        if: ${{ always() }}
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name=$github_workflow
          MESSAGE="${status:-bad} $workflow_name $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
