admin:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
manager:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
ingressController:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 400Mi
    requests:
      cpu: 10m
      memory: 350Mi
