admin:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
manager:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
ingressController:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 350Mi
